#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Text;
using Game.Editor.CodeGen;
using UnityEditor;
using UnityEngine;

namespace Game.Actions.Editor
{
    /// <summary>
    /// GameStateRegistry から enum GameState を生成するジェネレーター。
    /// </summary>
    public sealed class GameStateCodeGenerator
    {
        static GameStateCodeGenerator _instance;
        static GameStateCodeGenerator Instance => _instance ??= new GameStateCodeGenerator();

        GameStateRegistry _registry;

        const string MenuPath = "Tools/Game State/Generate";

        [MenuItem(MenuPath, priority = 10020)]
        public static void GenerateFromMenu()
        {
            var registry = GameStateRegistryLocator.GetOrCreate();
            var settings = FindOrCreateSettings();
            Generate(registry, settings);
        }

        public static void Generate(GameStateRegistry registry, GameStateSettings settings)
        {
            if (registry == null)
            {
                Debug.LogError("[GameStateCodeGenerator] Registry is null.");
                return;
            }

            Instance._registry = registry;
            Instance.GenerateInternal(settings);
        }

        public static GameStateSettings FindOrCreateSettings()
        {
            return TreeCodeGeneratorBase<GameStateSettings>.FindOrCreateSettings<GameStateSettings>(
                GameStateRegistryLocator.DefaultSettingsPath,
                "GameStateCodeGenerator");
        }

        void GenerateInternal(GameStateSettings settings)
        {
            var sb = new StringBuilder(4096);
            EmitHeader(sb, "GameStateCodeGenerator");

            var ns = GetNamespaceName(settings);
            var enumName = GetEnumName(settings);

            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");
            sb.AppendLine($"    public enum {enumName}");
            sb.AppendLine("    {");

            var usedNames = new HashSet<string>(StringComparer.Ordinal);
            foreach (var entry in BuildEntries())
            {
                EmitEntry(sb, entry, usedNames);
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            var outputPath = GetOutputPath(settings);
            WriteToFile(sb.ToString(), outputPath);
        }

        IEnumerable<EnumEntry> BuildEntries()
        {
            if (_registry == null)
                yield break;

            var nodes = _registry.Nodes
                .Where(n => n != null && !n.IsFolder)
                .OrderBy(n => n.StateId)
                .ThenBy(n => _registry.GetDisplayPath(n.Id), StringComparer.OrdinalIgnoreCase)
                .ToList();

            foreach (var node in nodes)
            {
                var path = _registry.GetDisplayPath(node.Id);
                var rawName = string.IsNullOrEmpty(path) ? node.Name : path.Replace("/", "_");
                var sanitized = TreeCodeGeneratorBase<GameStateSettings>.SanitizeIdentifier(rawName);
                if (string.IsNullOrWhiteSpace(sanitized))
                    sanitized = "_";

                yield return new EnumEntry
                {
                    Name = sanitized,
                    Value = node.StateId,
                    Description = node.Description ?? string.Empty,
                    Path = path ?? string.Empty,
                    Note = node.Note ?? string.Empty
                };
            }
        }

        void EmitEntry(StringBuilder sb, EnumEntry entry, HashSet<string> usedNames)
        {
            var name = TreeCodeGeneratorBase<GameStateSettings>.MakeUnique(entry.Name, usedNames);
            if (!string.IsNullOrEmpty(entry.Description))
            {
                sb.AppendLine($"        /// <summary>{TreeCodeGeneratorBase<GameStateSettings>.EscapeXml(entry.Description)}</summary>");
            }

            if (!string.IsNullOrEmpty(entry.Path) || !string.IsNullOrEmpty(entry.Note))
            {
                sb.AppendLine("        /// <remarks>");
                if (!string.IsNullOrEmpty(entry.Path))
                    sb.AppendLine($"        /// Path: {TreeCodeGeneratorBase<GameStateSettings>.EscapeXml(entry.Path)}");
                if (!string.IsNullOrEmpty(entry.Note))
                    sb.AppendLine($"        /// Note: {TreeCodeGeneratorBase<GameStateSettings>.EscapeXml(entry.Note)}");
                sb.AppendLine("        /// </remarks>");
            }

            sb.AppendLine($"        {name} = {entry.Value},");
        }

        static void EmitHeader(StringBuilder sb, string generatorName)
        {
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine($"// This file is generated by {generatorName}.");
            sb.AppendLine("// Do not edit manually.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
        }

        static string GetNamespaceName(GameStateSettings settings)
        {
            var ns = settings != null ? settings.NamespaceName : null;
            return string.IsNullOrWhiteSpace(ns) ? "Game.Actions" : ns.Trim();
        }

        static string GetEnumName(GameStateSettings settings)
        {
            var name = settings != null ? settings.RootClassName : null;
            var sanitized = TreeCodeGeneratorBase<GameStateSettings>.SanitizeIdentifier(name);
            return string.IsNullOrWhiteSpace(sanitized) ? "GameState" : sanitized;
        }

        static string GetOutputPath(GameStateSettings settings)
        {
            var path = settings != null ? settings.OutputPath : null;
            return string.IsNullOrWhiteSpace(path) ? "Assets/Game/Scripts/Generated/GameStates.g.cs" : path.Trim();
        }

        static void WriteToFile(string content, string outputPath)
        {
            var dir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
                Directory.CreateDirectory(dir);

            File.WriteAllText(outputPath, content, Encoding.UTF8);
            AssetDatabase.ImportAsset(outputPath);
            Debug.Log($"[GameStateCodeGenerator] Generated: {outputPath}");
        }

        sealed class EnumEntry
        {
            public string Name;
            public int Value;
            public string Description;
            public string Path;
            public string Note;
        }
    }
}
#endif
