// <auto-generated>
// ProjectEventIds.g.cs
//
// Global EventId definitions for SyncEventBus.
// Dense range [0, MaxEventIdExclusive). Update via the code generator alongside event specs.
// </auto-generated>

namespace Game.Common
{
    /// <summary>
    /// Global EventId map for all high-frequency sync events.
    /// IDs must remain dense (no gaps) and unique throughout the project.
    /// </summary>
    public static class ProjectEventIds
    {
        /// <summary>CollisionSystem per-frame hits.</summary>
        public const int Collision_Frame = 0;

        /// <summary>
        /// Exclusive upper bound for valid EventIds. Keep in sync with generated map.
        /// </summary>
        public const int MaxEventIdExclusive = 64;
    }
}
