#if UNITY_EDITOR
using System.Collections.Generic;
using System;
using System.Text;
using Game.Editor.CodeGen;
using Game.Editor.Registry;
using Game.Registry;
using UnityEditor;
using UnityEngine;


namespace Game.Scalar.Editor
{
    /// <summary>
    /// ScalarKeyRegistry から静的クラス (ScalarKeys.g.cs) を自動生成するユーティリティ。
    /// </summary>
    public sealed class ScalarKeyCodeGenerator : StringKeyCodeGeneratorBase<ScalarKeySettings>
    {
        // ----------------------------------------------------------------
        // シングルトンインスタンス
        // ----------------------------------------------------------------

        static ScalarKeyCodeGenerator _instance;
        static ScalarKeyCodeGenerator Instance => _instance ??= new ScalarKeyCodeGenerator();

        // ----------------------------------------------------------------
        // フィールド
        // ----------------------------------------------------------------

        ScalarKeyRegistry _registry;

        // ----------------------------------------------------------------
        // メニュー
        // ----------------------------------------------------------------

        const string MenuPath = "Tools/Scalar Keys/Generate";

        [MenuItem(MenuPath, priority = 10000)]
        public static void GenerateFromMenu()
        {
            var registry = ScalarKeyRegistryLocator.GetOrCreate();
            var settings = FindOrCreateSettings();
            Generate(registry, settings);
        }

        // ----------------------------------------------------------------
        // 公開API
        // ----------------------------------------------------------------

        /// <summary>
        /// コード生成を実行する。
        /// </summary>
        public static void Generate(ScalarKeyRegistry registry, ScalarKeySettings settings)
        {
            if (registry == null)
            {
                Debug.LogError("[ScalarKeyCodeGenerator] Registry is null.");
                return;
            }

            Instance._registry = registry;
            Instance.Generate(settings);
        }

        /// <summary>
        /// 設定を検索するか、なければ作成する。
        /// </summary>
        public static ScalarKeySettings FindOrCreateSettings()
        {
            return TreeCodeGeneratorBase<ScalarKeySettings>.FindOrCreateSettings<ScalarKeySettings>(
                "Assets/GameLib/SO/Scalar/ScalarKeySettings.asset",
                "ScalarKeyCodeGenerator");
        }

        // ----------------------------------------------------------------
        // 抽象メソッド実装
        // ----------------------------------------------------------------

        /// <inheritdoc/>
        protected override string GeneratorName => "ScalarKeyCodeGenerator";

        /// <inheritdoc/>
        protected override string DefaultNamespace => "Game.Scalar.Generated";

        /// <inheritdoc/>
        protected override string DefaultRootClassName => "ScalarKeys";

        /// <inheritdoc/>
        protected override string DefaultOutputPath => "Assets/GameLib/Script/Common/Scalar/Generated/ScalarKeys.g.cs";

        /// <inheritdoc/>
        protected override void EmitHeader(StringBuilder sb, string generatorName)
        {
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine($"// This file is generated by {generatorName}.");
            sb.AppendLine("// Do not edit manually.");
            sb.AppendLine("//");
            sb.AppendLine("// Alternative: ScalarKey を CSV ファイルからインポートすることも可能です。");
            sb.AppendLine("// CSV フォーマット: Type,Path,ExplicitKey,Description,Obsolete,Tags");
            sb.AppendLine("// ScalarKeyRegistry の Inspector から [Import from CSV] を実行してください。");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
        }

        /// <inheritdoc/>
        protected override CodeGenTreeNode BuildTree()
        {
            if (_registry == null) return new CodeGenTreeNode();

            var root = new CodeGenTreeNode();

            // parentId -> children マップを構築
            var parentMap = new Dictionary<string, List<ScalarKeyNode>>(StringComparer.Ordinal);
            foreach (var n in _registry.Nodes)
            {
                if (n == null) continue;
                var pid = n.ParentId ?? string.Empty;
                if (!parentMap.TryGetValue(pid, out var list))
                {
                    list = new List<ScalarKeyNode>();
                    parentMap[pid] = list;
                }
                list.Add(n);
            }

            // 再帰的にツリー構築
            CodeGenTreeNode BuildChildren(ScalarKeyNode node, string parentPath)
            {
                var seg = node.Name ?? string.Empty;
                var path = string.IsNullOrEmpty(parentPath) ? seg : $"{parentPath}/{seg}";

                var treeNode = new CodeGenTreeNode
                {
                    Node = new ScalarKeyNodeAdapter(node, _registry, path),
                    Path = path
                };

                if (parentMap.TryGetValue(node.Id, out var children))
                {
                    children.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.OrdinalIgnoreCase));
                    foreach (var c in children)
                    {
                        treeNode.Children.Add(BuildChildren(c, path));
                    }
                }

                return treeNode;
            }

            // ルート直下
            if (parentMap.TryGetValue(string.Empty, out var roots))
            {
                roots.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.OrdinalIgnoreCase));
                foreach (var r in roots)
                {
                    root.Children.Add(BuildChildren(r, string.Empty));
                }
            }

            return root;
        }

        /// <inheritdoc/>
        protected override IEnumerable<string> GetNodeCommentLines(ICodeGenNode node)
        {
            if (node is ScalarKeyNodeAdapter adapter)
            {
                return adapter.GetCommentLines();
            }
            return null;
        }

        // ----------------------------------------------------------------
        // ノードアダプター
        // ----------------------------------------------------------------

        /// <summary>
        /// ScalarKeyNode を ICodeGenNode にアダプトする。
        /// </summary>
        sealed class ScalarKeyNodeAdapter : ICodeGenNode
        {
            readonly ScalarKeyNode _node;
            readonly ScalarKeyRegistry _registry;
            readonly string _path;

            public ScalarKeyNodeAdapter(ScalarKeyNode node, ScalarKeyRegistry registry, string path)
            {
                _node = node;
                _registry = registry;
                _path = path;
            }

            public string Name => _node?.Name ?? string.Empty;
            public bool IsFolder => _node?.IsFolder ?? false;
            public string Description => _node?.Description ?? string.Empty;

            public string KeyValue
            {
                get
                {
                    if (_node == null || _node.IsFolder) return string.Empty;
                    return _registry.GetKeyString(_node);
                }
            }

            /// <summary>
            /// コメント行を取得する。
            /// </summary>
            public IEnumerable<string> GetCommentLines()
            {
                if (_node == null || _node.IsFolder)
                    yield break;

                // Path
                if (!string.IsNullOrEmpty(_path))
                {
                    yield return $"Path: {_path}";
                }
            }
        }
    }
}
#endif
