#nullable enable
using System.Collections.Generic;

namespace Game.Kernel.V21.Composition
{
    public static class KernelV2ComponentPlacementCatalog
    {
        static readonly KernelComponentPlacementDescriptor[] SharedGenerationPlacements =
        {
            new KernelComponentPlacementDescriptor(
                "Game.Kernel.Generation.KernelProjectionGenerator",
                KernelMappedComponentKind.ProjectionGenerator,
                KernelComponentPlacementScope.SharedGeneration,
                "IR normalization and verified projection stay outside both runtime kernels and feed them as a shared generation layer."),
        };

        static readonly KernelComponentPlacementDescriptor[] ApplicationPlacements =
        {
            new KernelComponentPlacementDescriptor(
                "Game.Kernel.Boot.KernelBootBoundary",
                KernelMappedComponentKind.BootBoundary,
                KernelComponentPlacementScope.Application,
                "Verified boot gate belongs to ApplicationKernel and is not reimplemented in SceneKernel."),
            new KernelComponentPlacementDescriptor(
                "Game.Kernel.Boot.KernelBootRuntimeSurfaceFactory",
                KernelMappedComponentKind.BootRuntimeSurfaceFactory,
                KernelComponentPlacementScope.Application,
                "Boot/runtime surface construction stays app-wide so scene-local kernels consume extracted runtime parts instead of rebuilding V2 shell logic."),
            new KernelComponentPlacementDescriptor(
                "Game.Kernel.Diagnostics.KernelDiagnosticService",
                KernelMappedComponentKind.DiagnosticService,
                KernelComponentPlacementScope.Application,
                "ApplicationKernel owns the app-wide diagnostic sink and exposes it to scene-local kernels."),
            new KernelComponentPlacementDescriptor(
                "Game.Kernel.Boot.KernelBootManifest",
                KernelMappedComponentKind.BootManifest,
                KernelComponentPlacementScope.Application,
                "Selected boot manifest is application-wide state and must not move into SceneKernel."),
            new KernelComponentPlacementDescriptor(
                "Game.Kernel.Boot.KernelProfile",
                KernelMappedComponentKind.KernelProfile,
                KernelComponentPlacementScope.Application,
                "Selected kernel profile is application-wide state and must not move into SceneKernel."),
        };

        static readonly KernelComponentPlacementDescriptor[] ScenePlacements =
        {
            new KernelComponentPlacementDescriptor(
                "Game.Kernel.Boot.KernelBootRuntimeSurface",
                KernelMappedComponentKind.BootRuntimeSurface,
                KernelComponentPlacementScope.Scene,
                "SceneKernel consumes the verified runtime surface generated by the app-wide boot layer and exposes only scene-local boundaries from it."),
            new KernelComponentPlacementDescriptor(
                "Game.Kernel.Boot.KernelRuntimeServiceGraph",
                KernelMappedComponentKind.RuntimeServiceGraph,
                KernelComponentPlacementScope.Scene,
                "Verified service graph runtime becomes the scene-local ownership/resolution boundary."),
            new KernelComponentPlacementDescriptor(
                "Game.Kernel.Boot.KernelRuntimeScopeGraph",
                KernelMappedComponentKind.RuntimeScopeGraph,
                KernelComponentPlacementScope.Scene,
                "Verified scope graph runtime becomes the scene-local entity/scope boundary."),
            new KernelComponentPlacementDescriptor(
                "Game.Kernel.Boot.KernelLifecycleDispatcher",
                KernelMappedComponentKind.LifecycleDispatcher,
                KernelComponentPlacementScope.Scene,
                "Lifecycle dispatch stays scene-local and is driven from precomputed plans."),
            new KernelComponentPlacementDescriptor(
                "Game.Kernel.Boot.KernelLifecyclePlanResolver",
                KernelMappedComponentKind.LifecyclePlanResolver,
                KernelComponentPlacementScope.Scene,
                "Scene-local lifecycle plan resolution is derived from the verified runtime surface, not from runtime scans."),
        };

        public static IReadOnlyList<KernelComponentPlacementDescriptor> All => new[]
        {
            SharedGenerationPlacements[0],
            ApplicationPlacements[0],
            ApplicationPlacements[1],
            ApplicationPlacements[2],
            ApplicationPlacements[3],
            ApplicationPlacements[4],
            ScenePlacements[0],
            ScenePlacements[1],
            ScenePlacements[2],
            ScenePlacements[3],
            ScenePlacements[4],
        };

        public static IReadOnlyList<KernelComponentPlacementDescriptor> SharedGeneration => SharedGenerationPlacements;

        public static IReadOnlyList<KernelComponentPlacementDescriptor> Application => ApplicationPlacements;

        public static IReadOnlyList<KernelComponentPlacementDescriptor> Scene => ScenePlacements;
    }
}
