#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.Text;
using Game.Editor.CodeGen;
using Game.Editor.Registry;
using UnityEditor;
using UnityEngine;

namespace Game.EventKey.Editor
{
    // ================================================================
    // EventKeyCodeGenerator - EventKeyRegistry からコード生成
    // ================================================================

    /// <summary>
    /// EventKeyRegistry から静的 string クラスを生成するジェネレーター。
    /// </summary>
    public sealed class EventKeyCodeGenerator : StringKeyCodeGeneratorBase<EventKeySettings>
    {
        // ----------------------------------------------------------------
        // シングルトンインスタンス
        // ----------------------------------------------------------------

        static EventKeyCodeGenerator _instance;
        static EventKeyCodeGenerator Instance => _instance ??= new EventKeyCodeGenerator();

        // ----------------------------------------------------------------
        // フィールド
        // ----------------------------------------------------------------

        EventKeyRegistry _registry;

        // ----------------------------------------------------------------
        // メニュー
        // ----------------------------------------------------------------

        const string MenuPath = "Tools/Event Keys/Generate";

        [MenuItem(MenuPath, priority = 10010)]
        public static void GenerateFromMenu()
        {
            var registry = EventKeyRegistryLocator.GetOrCreate();
            var settings = FindOrCreateSettings();
            Generate(registry, settings);
        }

        // ----------------------------------------------------------------
        // 公開API
        // ----------------------------------------------------------------

        /// <summary>
        /// コード生成を実行する。
        /// </summary>
        public static void Generate(EventKeyRegistry registry, EventKeySettings settings)
        {
            if (registry == null)
            {
                Debug.LogError("[EventKeyCodeGenerator] Registry is null.");
                return;
            }

            Instance._registry = registry;
            Instance.Generate(settings);
        }

        /// <summary>
        /// 設定を検索するか、なければ作成する。
        /// </summary>
        public static EventKeySettings FindOrCreateSettings()
        {
            return TreeCodeGeneratorBase<EventKeySettings>.FindOrCreateSettings<EventKeySettings>(
                "Assets/GameLib/SO/Event/EventKeySettings.asset",
                "EventKeyCodeGenerator");
        }

        // ----------------------------------------------------------------
        // 抽象メソッド実装
        // ----------------------------------------------------------------

        /// <inheritdoc/>
        protected override string GeneratorName => "EventKeyCodeGenerator";

        /// <inheritdoc/>
        protected override string DefaultNamespace => "Game.Events.Generated";

        /// <inheritdoc/>
        protected override string DefaultRootClassName => "EventKeys";

        /// <inheritdoc/>
        protected override string DefaultOutputPath => "Assets/Library/Script/Generated/EventKeys.g.cs";

        /// <inheritdoc/>
        protected override void EmitHeader(StringBuilder sb, string generatorName)
        {
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine($"// This file is generated by {generatorName}.");
            sb.AppendLine("// Do not edit manually.");
            sb.AppendLine("//");
            sb.AppendLine("// Alternative: EventKey を CSV ファイルからインポートすることも可能です。");
            sb.AppendLine("// CSV フォーマット: Type,Path,ExplicitKey,Description");
            sb.AppendLine("// EventKeyRegistry の Inspector から [Import from CSV] を実行してください。");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
        }

        /// <inheritdoc/>
        protected override CodeGenTreeNode BuildTree()
        {
            if (_registry == null) return new CodeGenTreeNode();

            var root = new CodeGenTreeNode();

            // parentId -> children マップを構築
            var parentMap = new Dictionary<string, List<EventKeyNode>>(StringComparer.Ordinal);
            foreach (var n in _registry.Nodes)
            {
                if (n == null) continue;
                var pid = n.ParentId ?? string.Empty;
                if (!parentMap.TryGetValue(pid, out var list))
                {
                    list = new List<EventKeyNode>();
                    parentMap[pid] = list;
                }
                list.Add(n);
            }

            // 再帰的にツリー構築
            CodeGenTreeNode BuildChildren(EventKeyNode node, string parentPath)
            {
                var seg = node.Name ?? string.Empty;
                var path = string.IsNullOrEmpty(parentPath) ? seg : $"{parentPath}/{seg}";

                var treeNode = new CodeGenTreeNode
                {
                    Node = new EventKeyNodeAdapter(node, path),
                    Path = path
                };

                if (parentMap.TryGetValue(node.Id, out var children))
                {
                    children.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.OrdinalIgnoreCase));
                    foreach (var c in children)
                    {
                        treeNode.Children.Add(BuildChildren(c, path));
                    }
                }

                return treeNode;
            }

            // ルート直下
            if (parentMap.TryGetValue(string.Empty, out var roots))
            {
                roots.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.OrdinalIgnoreCase));
                foreach (var r in roots)
                {
                    root.Children.Add(BuildChildren(r, string.Empty));
                }
            }

            return root;
        }

        /// <inheritdoc/>
        protected override IEnumerable<string> GetNodeCommentLines(ICodeGenNode node)
        {
            if (node is EventKeyNodeAdapter adapter)
            {
                return adapter.GetCommentLines();
            }
            return null;
        }

        // ----------------------------------------------------------------
        // ノードアダプター
        // ----------------------------------------------------------------

        /// <summary>
        /// EventKeyNode を ICodeGenNode にアダプトする。
        /// </summary>
        sealed class EventKeyNodeAdapter : ICodeGenNode
        {
            readonly EventKeyNode _node;
            readonly string _path;

            public EventKeyNodeAdapter(EventKeyNode node, string path)
            {
                _node = node;
                _path = path;
            }

            public string Name => _node?.Name ?? string.Empty;
            public bool IsFolder => _node?.IsFolder ?? false;
            public string Description => _node?.Description ?? string.Empty;

            public string KeyValue
            {
                get
                {
                    if (_node == null || _node.IsFolder) return string.Empty;

                    // ExplicitKey があればそれを使用、なければパスをキーとして使用
                    if (!string.IsNullOrEmpty(_node.ExplicitKey))
                        return _node.ExplicitKey;

                    return (_path ?? string.Empty).Replace('/', '.');
                }
            }

            /// <summary>
            /// コメント行を取得する。
            /// </summary>
            public IEnumerable<string> GetCommentLines()
            {
                if (_node == null || _node.IsFolder)
                    yield break;

                // Path
                if (!string.IsNullOrEmpty(_path))
                {
                    yield return $"Path: {_path}";
                }

                // ExplicitKey がある場合は表示
                if (!string.IsNullOrEmpty(_node.ExplicitKey))
                {
                    yield return $"ExplicitKey: {_node.ExplicitKey}";
                }
            }
        }
    }
}
#endif
